### ISSUE TITLE
Review PhantomJS driver support

### ISSUE THREAD

**Issue by davehunt** [davehunt/pytest-selenium#10]
We may need to improve the experience when running against PhantomJS. At very least we should provide a decent guide to getting PhantomJS configured for running tests. We should also see if there's a way to get the PhantomJS tests running on Travis-CI.

**Comment by bobsilverberg** [comment]
Closed via https://github.com/davehunt/pytest-selenium/commit/22a98e72d302700f53058f75b53974fca477386c
