### ISSUE TITLE
Revisit command line capability support

### ISSUE THREAD

**Issue by davehunt** [davehunt/pytest-selenium#16]
At the moment we accept capabilities on the command line using `--capability=key:value` and we cast the value to an integer or a boolean if it looks like one. This means we can't specify a value that looks like an integer but we want to be treated as a string. It also means we can't specify lists or dictionaries as values.

Previously, in pytest-mozwebqa we had a `--capabilties=json` command line option, which took a string representation of a JSON object and created a dictionary from that in Python. If I recall correctly, the problems this cause were that string escaping turned out to be a real pain across platforms, and we had to specify all of the capabilities in one command line option.

I'd like to solicit suggestions on how we can improve this. Doing so will allow us to replace the Chrome options with capabilities on the command line, and replace the Sauce Labs tags configuration option with command line capabilties.

Any thoughts @bobsilverberg, @justinpotts?

**Comment by davehunt** [comment]
One thought I had was to use [nargs](https://docs.python.org/2.7/library/argparse.html#nargs) and allow multiple arguments for the `--capability` command line option. We could then support something like:

    py.test --capability key value [value ...]

Whilst this should allow us to support lists, it doesn't solve the issue of intepreting boolean and integers, or passing complex values such as dictionaries.

**Comment by davehunt** [comment]
Another option is to add `--complex-capability` that takes a JSON string. Then `--capabilty` would be for settings string values (and potentially lists of strings based on my previous comment), and anything else would be considered 'complex'. We'd have to tackle the escaping on various platforms though, but maybe that's worth doing (it shouldn't be too hard, just a case of getting the correct syntax).

**Comment by justinpotts** [comment]
Is there a way to specify which options hold those types of values? For example, we have browserName, which is a string. Then if a user specified an option such as recordVideo, which is a boolean, we code check that in the code.

    string_options = ['browserName']
    boolean_options = ['recordVideo', 'recordScreenshots']

    for item in capabilites:
        if key in string_options:
            convert item to string
        elif key in boolean_options:
            convert item to boolean

Don't know if that'll work, but I think it would allow us to grab types.

**Comment by davehunt** [comment]
> Is there a way to specify which options hold those types of values? For example, we have browserName, which is a string. Then if a user specified an option such as recordVideo, which is a boolean, we code check that in the code.

We'd have to maintain a list of keys and types, and they may even differ between services. So although this is possible, I'm unsure if it's the route we'd want to go.

**Comment by justinpotts** [comment]
@davehunt, we could also use a JSON Schema which would prevent us form having to do so much type-checking in the code.

http://json-schema.org/example1.html

**Comment by davehunt** [comment]
Thanks for all your help @bobsilverberg and @justinpotts. This has been addressed and I'm going to close the issue.
