### ISSUE TITLE
Possible to skip _verify_base_url check?

### ISSUE THREAD

**Issue by birdsarah** [davehunt/pytest-selenium#25]
My tests dynamically start their own server and so the _verify_base_url check seems to fail. 

Is it possible to skip it? If not, would you be up for an option to skip it?

**Comment by davehunt** [comment]
You should be able to just reimplement the fixture as s noop.

Dave

**Comment by birdsarah** [comment]
Thanks @davehunt! I'm a little surprised the above works. I had to make sure my function was scoped the same.

**Comment by birdsarah** [comment]
edit.
