### ISSUE TITLE
Selenium plugin listed twice

### ISSUE THREAD

**Issue by birdsarah** [davehunt/pytest-selenium#32]
Hi,

When using pytest-selenium and running my test, I see this at the start: 

```sh
platform darwin -- Python 3.4.3 -- py-1.4.30 -- pytest-2.7.2
rootdir: /bokeh/bokeh, inifile: setup.cfg
plugins: html, selenium, selenium, variables
collected 410 items
```

I think it's disconcerting that the plugins line reads: `plugins: html, selenium, selenium, variables`

I think it comes from having the separate `safety.py` file.

**Comment by davehunt** [comment]
It might be a pytest bug. I have pytest-xdist installed in a fresh virtual environment and I see that listed three times. @RonnyPfannschmidthave you seen this before?

```sh
platform darwin -- Python 2.7.10 -- py-1.4.30 -- pytest-2.7.2
rootdir: /Users/dhunt/workspace/mozwebqa-examples, inifile: 
plugins: flask, html, selenium, selenium, variables, xdist, xdist, xdist
gw0 [6] / gw1 [6] / gw2 [6] / gw3 [6]
scheduling tests via LoadScheduling
```

**Comment by RonnyPfannschmidt** [comment]
Fixed in pytest master
Current pytest does show the distribution of each entry point without deduplication

**Comment by birdsarah** [comment]
brilliant - thanks!
