### ISSUE TITLE
Unable to decode non-ascii characters

### ISSUE THREAD

**Issue by rarelam** [davehunt/pytest-selenium#33]
Hi, there is an error by plugin about fail to decode non-ascii characters.

Please refer to the attachment.

![78a87012-589a-11e5-8068-f16891213dc3](https://cloud.githubusercontent.com/assets/1460421/9869163/9262ec5a-5bb3-11e5-8ac6-0c3d243a8d22.png)

**Comment by rarelam** [comment]
Hi, 

will it possible to resolve the problem by adding .encode('ascii', 'ignore')?

```python
format_log(log), '%s Log' % log_type.title()))
```
on https://github.com/davehunt/pytest-selenium/blob/master/pytest_selenium/pytest_selenium.py#L125


by adding **.encode('ascii', 'ignore')**
```python
format_log(log.encode('ascii', 'ignore')), '%s Log' % log_type.title()))
```

But I'm not sure it is safe to ignore or maybe it wouldn't solve the encoding issue at all.

**Comment by davehunt** [comment]
Please try 1.0b2 from PyPI. Thanks.

**Comment by rarelam** [comment]
It is working. Thank you.
