### ISSUE TITLE
[Feature request] Add "html" to setup.cfg

### ISSUE THREAD

**Issue by rarelam** [davehunt/pytest-selenium#37]
Hi,

Currently if I want to generate HTML report, I need to add "--html" on command line, will it possible to adding this on setup.cfg?

Thanks.

**Comment by davehunt** [comment]
The HTML report is generated by [pytest-html](https://pypi.python.org/pypi/pytest-html) so any issues should be raised there. That said, you should be able to add this to [addopts](http://pytest.org/latest/customize.html#adding-default-options) in `setup.cfg`.
