### ISSUE TITLE
Fix deprecation warning

### ISSUE THREAD

**Issue by kottenator** [davehunt/pytest-selenium#45]
I have `pytest==2.8.4` and `pytest-selenium==1.0` installed.

When I run `py.test`, I get the following warning:

    WI1 /home/username/.virtualenvs/login/lib/python3.4/site-packages/pytest_selenium/pytest_selenium.py:90 
    'pytest_runtest_makereport' hook uses deprecated __multicall__ argument

**Comment by davehunt** [comment]
Thanks for the issue report. This has been fixed in https://github.com/davehunt/pytest-selenium/commit/4beb76c56264a9964f019a9530c0ca97eaa2b391 and will be available in 1.1, which I hope to release next week.
