### ISSUE TITLE
Prevent firefox launching the "learnmore" page

### ISSUE THREAD

**Issue by birdsarah** [davehunt/pytest-selenium#48]
I guess this is a two part issue:

1) How can I prevent firefox from launching the learn more page every time it opens - it's wasting time and bandwidth on my tests
2) Can we add this as a flag into pytest-selenium?

**Comment by rarelam** [comment]
I guess this is your issue:

please check this commit: https://github.com/SeleniumHQ/selenium/commit/cc0647aa5092aa46df6118999a24a5dc4623b966

**Comment by birdsarah** [comment]
Thanks for the quick response @rarelam, any tips on how I configure this in my test suite?

**Comment by rarelam** [comment]
I don't think we can do anything for now, unless selenium has released new version. :(

**Comment by bobsilverberg** [comment]
I may be wrong, but I believe all that Selenium commit does is create a default value for that pref in the Firefox profile, so you should be able to do that yourself by setting that pref into the profile programatically before launching Firefox.

**Comment by davehunt** [comment]
A new release of Selenium is needed to pick up the new default preference values, however you can use `--firefox-preference startup.homepage_welcome_url.additional about:blank` on the command line to set the preference yourself.

**Comment by stathmarxis** [comment]
put this in your code if you work in java also it is similar and in other languages

    FirefoxProfile profile=new FirefoxProfile();
    profile.setPreference("javascript.options.showInConsole", true);
    profile.setPreference("network.http.max-connections-per-server", 100);
    profile.setPreference("browser.startup.homepage", "about:blank");
    profile.setPreference("startup.homepage_welcome_url", "about:blank");
    profile.setPreference("startup.homepage_welcome_url.additional", "about:blank");
    profile.setPreference("webdriver_accept_untrusted_certs", true);
    profile.setPreference("webdriver_assume_untrusted_issuer", true);
    WebDriver  driver = new FirefoxDriver(profile);

pllzz let me know if i help y

**Comment by birdsarah** [comment]
thanks so much @davehunt that works great!
