### ISSUE TITLE
Clean up command line options

### ISSUE THREAD

**Issue by davehunt** [davehunt/pytest-selenium#5]
I'd like to revisit and clean up the existing command line options. Here are the current options, with some suggestions for improvements:

* **--baseurl** - Rename to --base-url
* **--skipurlcheck** - I think we should remove this. I believe it was added for testing sites that are not http(s) such as about:support, etc. I would be inclined to reimplement this as a protocol check in _verify_base_url
* **--host** - leave this as it is
* **--port** - leave this as it is
* **--driver** - leave this as it is for now, but I'd like to have a local default - we could potentially determine which browsers are present and conveniently pick one. I don't think we should assume the user will have a Selenium server running
* **--capability** - leave this as it is
* **--chromepath** - rename to --driver-path
* **--firefoxpath** - rename to --driver-path
* **--firefoxpref** - rename to --firefox-pref
* **--profilepath** rename to --firefox-profile
* **--extension** rename to --browser-extension
* **--chromeopts** - rename to repeatable --chrome-option argument
* **--operapath** - rename to --driver-path
* **--browsername** - remove and document using --capability for Grid, Sauce Labs, and BrowserStack
* **--browserver** - remove and document using --capability for Grid, Sauce Labs, and BrowserStack
* **--platform** - remove and document using --capability for Grid, Sauce Labs, and BrowserStack
* **--build** - replace with environment variable (BUILD_ID in Jenkins, TRAVIS_BUILD_NUMBER in Travis, etc)
* **--untrusted** - remove and revisit in the future if it's needed
* **--proxyhost** - rename to --proxy-host
* **--proxyport** - rename to --proxy-port
* **--eventlistener** - rename to --event-listener
* **--sensitiveurl** - rename to --sensitive-url and allow configuration from environment variable
* **--destructive** - leave this as it is

**Comment by davehunt** [comment]
I'm keen for feedback here. /cc @bobsilverberg, @justinpotts, @codingjoe

**Comment by codingjoe** [comment]
I think it would be great to offer most options as an environment variable (security) or pytest-conf variable as well.

**Comment by davehunt** [comment]
All command line options *should* be able to be set using PYTEST_ADDOPTS environment variable, however I agree that it's nice to have dedicated variable names for most. What is the pytest-conf you mention, is that a plugin (I couldn't find it).

**Comment by davehunt** [comment]
> **--driver** - leave this as it is for now, but I'd like to have a local default - we could potentially determine which browsers are present and conveniently pick one. I don't think we should assume the user will have a Selenium server running

Second thoughts on this, I don't think we can expect users to have any of the drivers available - the only one that's convenient at the moment is Firefox but in the future this will be a separate download like the others. Maybe we should just remove the default value, and prompt the user with a list of valid drivers if the value is omitted.

**Comment by codingjoe** [comment]
@davehunt nope, there isn't a pytest-conf, I was talking about `PYTEST_ADDOPTS`.

**Comment by bobsilverberg** [comment]
@davehunt I like all of your suggestions. The only one I'd question is `--build` as I actually sometimes use that locally so I can easily identify my own tests running at Saucelabs. I wouldn't want to have to set an environment variable for that for a local run, although I certainly could if need be. Do you feel that one is important to remove?

**Comment by davehunt** [comment]
> @davehunt I like all of your suggestions. The only one I'd question is --build as I actually sometimes use that locally so I can easily identify my own tests running at Saucelabs. I wouldn't want to have to set an environment variable for that for a local run, although I certainly could if need be. Do you feel that one is important to remove?

Well, it's just that it's related to Sauce Labs (or CI) and not Selenium. It just feels like this plugin is the wrong place for it. I think I could probably be convinced, but maybe there's a better solution out there?

**Comment by bobsilverberg** [comment]
@davehunt Valid point, although that doesn't really address the fact that you suggested making it available via an environment variable. Would the plugin still do something with that env var, or would its existence just work and bypass the plugin?

**Comment by davehunt** [comment]
To be honest I'm looking for suggestions. There's some missing context from a discussion with @justinpotts:

> This is currently only used in saucelabs.py, I was going to suggest pull it out of the environment there, but I think it could be messy. Maybe leave this one for now.

Here's the code:
https://github.com/davehunt/pytest-selenium/blob/master/pytest_selenium/cloud/saucelabs.py#L58

Aha, and there's the solution, let's just remove it and document using `--capability=build:${VARIABLE}`

**Comment by justinpotts** [comment]
@davehunt So we'll just take out --build, and then they will use that --capability option to specify which build to use?

**Comment by davehunt** [comment]
Yeah, I like that!

**Comment by justinpotts** [comment]
@davehunt In --sensitiveurl, it's already being specified from an environment variable. Were you thinking to change it to something different?

**Comment by davehunt** [comment]
Ah, awesome - that's fine as it is then.
