### ISSUE TITLE
Implement cloud providers as plugins

### ISSUE THREAD

**Issue by davehunt** [davehunt/pytest-selenium#50]
I think it would make sense for the various cloud providers (Sauce Labs, BrowserStack, TestingBot) to be reimplemented as plugins. This would give more flexibility than the current implementation as each provider has different features and API models. I'm not sure of the best approach, but suspect that we could implement custom hooks in the main plugin to support these additional driver plugins.

**Comment by bobsilverberg** [comment]
This seems like a good idea to me. +1

**Comment by davehunt** [comment]
Fixed by #51
