### ISSUE TITLE
Allow `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` environment variables 

### ISSUE THREAD

**Issue by birdsarah** [davehunt/pytest-selenium#53]
Currently, when setting up saucelabs with pytest-selenium, you can provide the environment variables `SAUCELABS_USERNAME` and `SAUCELABS_API_KEY`. If you need to use SauceLabs connect (which I do) then when setting up travis you provide the same information but with slightly differently named environment variable `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` https://docs.travis-ci.com/user/sauce-connect/#Setting-up-Sauce-Connect. 

I don't want to get rid of the existing env names, it would be nice if I could also use `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` too.

**Comment by davehunt** [comment]
You should be able to export new variables with the value of existing variables, such as:

```bash
export SAUCELABS_USERNAME=${SAUCE_USERNAME}
export SAUCELABS_API_KEY=${SAUCE_ACCESS_KEY}
```

Alternatively, you could create a `conftest.py` to switch the environment variables used by pytest-selenium:

```python
import os
def pytest_addoption(parser):
parser.addini('sauce_labs_username',
              help='sauce labs username',
              default=os.getenv('SAUCE_USERNAME'))
parser.addini('sauce_labs_api_key',
              help='sauce labs api key',
              default=os.getenv('SAUCE_ACCESS_KEY'))
```

Finally, I'd support a patch that checked the additional environment variable names.

**Comment by birdsarah** [comment]
Agreed all of the above would work. Adding four things to TravisCI was not that much drama.

If I feel inspired I'll certainly work on a patch. I guess the only weirdness is then, as a library, you have two ways of doing the same thing........not sure how I feel about that (I know I suggested it)

**Comment by davehunt** [comment]
I'm going to close this issue as I don't think anybody is likely to work on it, and there are several alternatives mentioned.
