### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by davehunt** [davehunt/pytest-selenium#6]

**Comment by codingjoe** [comment]
:+1:

**Comment by birdsarah** [comment]
Hi @davehunt, can you elaborate a little more on what's missing for py3? I've been happily using pytest-selenium over the past week or so (specifically with the fixes from @codingjoe in) with py23 code on python 3.4.

**Comment by davehunt** [comment]
Hey @birdsarah we just need to get the tests passing in Travis CI:  https://travis-ci.org/davehunt/pytest-selenium it looks like there's just one failing test at the moment and an issue with webserver.py that's preventing the process from stopping.

**Comment by davehunt** [comment]
Patch ready in #55

**Comment by davehunt** [comment]
Fixed in https://github.com/davehunt/pytest-selenium/commit/ebf14842132db40f533391364cb84ba7d7def754
