### ISSUE TITLE
Question: Shorten the browserName command

### ISSUE THREAD

**Issue by rarelam** [davehunt/pytest-selenium#61]
Hi,

Currently I run this test command below:

> py.test --driver Remote --capability browserName firefox --html=Results\report.html

However, can I ask to add a feature to accept shorten browser name?
Example: 
for firefox, it can accept firefox, ff
for chrome, it is accept command with chrome, gc

Thank you.

**Comment by davehunt** [comment]
You can implement this yourself by creating a `conftest.py` file and setting the capabilities directly. A quick example that works for me:

```python
def pytest_addoption(parser):
    group = parser.getgroup('selenium', 'selenium')
    group._addoption('--fx', action='store_true', help='shortcut for --capability browserName Firefox')
    group._addoption('--gc', action='store_true', help='shortcut for --capability browserName Chrome')


def pytest_configure(config):
    if config.getoption('fx'):
        config.option.capabilities.append(('browserName', 'Firefox'))
    if config.getoption('gc'):
        config.option.capabilities.append(('browserName', 'Chrome'))
```

As this is trivial to do locally, and users are likely to have their own preferences, I don't think it's worth providing these shortcuts in pytest-selenium.
