### ISSUE TITLE
base_url not working without @pytest.mark.nondestructive

### ISSUE THREAD

**Issue by davidemoro** [davehunt/pytest-selenium#62]
Hi,

I tried to setup a ``base_url`` configuration following step by step the latest documentation:
* http://pytest-selenium.readthedocs.org/en/latest/user_guide.html#specifying-a-base-url

Providing the ``base_url`` configuration using a ``setup.cfg`` file or using the command line option ``--base-url`` didn't worked for me. Let's suppose to have a ``base_url`` option set to ``http://google.com``.

Dummy test code:
```
def test_dummy(base_url, selenium):
    assert 1
```

Expected result (try with ``py.test --driver Firefox`` plus ``setup.cfg`` for example):
* ``base_url`` should be equals to ``http://google.com``

Instead I got:
* the test is skipped (not executed)

I had a look at the ``pytest-selenium`` tests and I've seen that you've been using a ``@pytest.mark.nondestructive`` decorator and now it works fine:
```
import pytest

@pytest.mark.nondestructive
def test_dummy(base_url, selenium):
    assert 1
```

So my question is: is there a problem with the documentation or this is a bug?
Thanks in advance.

**Comment by davehunt** [comment]
See the documentation section on [sensitive environments](http://pytest-selenium.readthedocs.org/en/latest/user_guide.html#sensitive-environments).

Concerning destructive tests:
> To avoid accidental changes being made to sensitive environments such as your production instances, all tests are assumed to be destructive. Any destructive tests attempted to run against a sensitive environment will be skipped.

Concerning sensitive environments:
> Sensitive environments are indicated by a regular expression applied to the base URL or any URLs discovered in the history of redirects when retrieving the base URL. By default this matches all URLs.

To disable sensitive URL checking, set the sensitive URL regex to something that won't match your base URL. The defaults are to reduce the risk of writing a test that makes irreversible changes to a website and running that test against a production instance.

I've added a note (https://github.com/davehunt/pytest-selenium/commit/20da26fdb66b9dc3aa1518a25edb35bf8ae83ed2) to the base URL documentation in an attempt to make this a little clearer.

**Comment by davidemoro** [comment]
Hi @davehunt, thank you very much!
