### ISSUE TITLE
change selenium fixture to be "class"/"module" scope ?

### ISSUE THREAD

**Issue by yuri1992** [davehunt/pytest-selenium#63]

**Comment by ProProgrammer** [comment]
Hey, didn't quite get the issue. `pytest` allows you to scope at `module` level as follows: `@pytest.fixture(scope="module")` but I think not at `class` level. What exactly are you trying to achieve? Elaborate please.

**Comment by yuri1992** [comment]
selenium fixture is using `function` scope, what mean that for each test it will open a new webdriver.
I thinks you should have option to share the same webdriver between few tests.

`pytest` allow to set scope to `class` level as well. (http://pytest.org/latest/fixture.html#fixture)

**Comment by ProProgrammer** [comment]
If you want to use same webdriver instance across different tests, you could put those tests within same module and scope the driver fixture it at `module` level or you could use `session` scope which would instantiate the browser only once and use that for all selenium based tests in that particular session.

**Comment by yuri1992** [comment]
Sorry for not be cleared, pytest-selenium have selenium fixture.
https://github.com/davehunt/pytest-selenium/blob/master/pytest_selenium/pytest_selenium.py
(which already configured to support pytest args, like --driver firefox, etc)

as you can this fixture scoped to `function` level.
I thinks this should be at higher fixture level.

**Comment by jmakov** [comment]
Same problem here - the scope level needs to be exposed.

**Comment by davehunt** [comment]
See https://github.com/davehunt/pytest-selenium/issues/59 for a similar issue regarding using a session scope. Generally reusing the browser is a bad idea, but it is possible to re-scope the fixtures as demonstrated in the comments for the mentioned issue. As far as I'm aware this is the only way to redefine the scope of plugin fixtures within pytest, however if there is a more elegant way I'd consider merging a pull request that allows it.

**Comment by davehunt** [comment]
According to a core developer of https://github.com/pytest-dev/pytest there is currently no way to do this. There are plans to improve fixtures, and ultimately allow them to support multiple scopes, but until then https://github.com/davehunt/pytest-selenium/issues/59#issuecomment-200338319 is my best suggestion. Of course, I still firmly believe that each test should have a clean browser instance for your tests to have maximum reliability and ability to run in parallel.

**Comment by yuri1992** [comment]
Thank you Dave.

**Comment by danizen** [comment]
There is a way to do this - you can use a dynamic scope function.

Something like this:

```python
     pytest_configure(config):
         # ... existing logic
         global driver_scope
         driver_scope = something_that_depends_on_config
```

Later on, the dynamic scope function can return the global driver scope.

**Comment by Dude-X** [comment]
@yuri1992 As danzien mentions, beginning with Pytest 5.0, dynamic scope makes this a lot easier than weird fixture tricks.

**Comment by danizen** [comment]
@yuri1992 and @davehunt , I also gave some thought as to how to save the webdriver instance into the node for the test report.  I have no time to do a pull or anything, but for my own package internal to U.S. NLM, I'm doing something like this, but I'm not sure it will work yet:

```python
@pytest.fixture(autouse=True)
def annotate_node_with_driver(request):
    """
    This fixture detects whether a test or its parent is using a selenium driver, and marks
    the node with the driver instance.
    """
    if 'driver' in request.fixturenames:
        request.node._driver = request.getfixturevalue('driver')
```
