### ISSUE TITLE
Review Chrome driver support

### ISSUE THREAD

**Issue by davehunt** [davehunt/pytest-selenium#8]
I haven't used the Chrome support for a long time, and I suspect that we may need to improve the experience. At very least we should provide a decent guide to getting Chrome configured for running tests. We should also see if there's a way to get the Chrome tests running on Travis-CI.

**Comment by davehunt** [comment]
ChromeDriver documentation: https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by justinpotts** [comment]
@davehunt, all good here, minus the addition to the documentation specifying where to download ChromeDriver to, concerning the "PATH" error. What do you want me to do about this?

**Comment by justinpotts** [comment]
Closed with Pull #18
