### ISSUE TITLE
Review Opera driver support

### ISSUE THREAD

**Issue by davehunt** [davehunt/pytest-selenium#9]
Opera has changed substantially since I last tested it, and I suspect that we may need to improve the experience. At very least we should provide a decent guide to getting Opera configured for running tests. We should also see if there's a way to get the Opera tests running on Travis-CI.

**Comment by justinpotts** [comment]
@davehunt + @bobsilverberg: Looks like operadriver has become part of Selenium itself. Do we still need to install the driver itself? That's possibly why I can't find a download anywhere...

However, running with --driver=opera yields the same path error we were talking about earlier:

`WebDriverException: Message: 'operadriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

Is there another way to run this or am I going about it the wrong way?

**Comment by justinpotts** [comment]
Closing, as we have decided to drop Opera support.
